/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.edu.ifsc.sj.engtelecom.poo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
